name: Build firmware according to user config file

on:
  workflow_dispatch:
  push:
    paths:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cargo-bins/cargo-binstall@main
      - uses: actions/checkout@v3
      - name: Install libssl
        run: wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2_amd64.deb && sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2_amd64.deb
      - name: Install flip-link and cargo-make
        run: cargo binstall cargo-make flip-link -y
      - name: Build firmware
        working-directory: ./rmk
        run: cargo build --release
      - name: Build uf2 firmware
        working-directory: ./rmk
        run: cargo make uf2 --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware_uf2
          path: ergo9000/*.uf2
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware_hex
          path: ergo9000/*.hex

